# Generated by Django 3.2 on 2022-06-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='genre',
            new_name='books',
        ),
    ]
