# Generated by Django 3.2 on 2022-06-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_sale_sale_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_name',
            new_name='name',
        ),
    ]
