# Generated by Django 3.2 on 2022-06-26 22:42

from django.db import migrations, models
import sale.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_rename_sale_name_sale_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='end_date',
            field=models.DateField(validators=[sale.validators.date_not_in_past]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
