# Generated by Django 3.2 on 2022-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=254)),
                ('isbn13', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('subtitle', models.CharField(blank=True, max_length=254, null=True)),
                ('authors', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=254)),
                ('publication_date', models.DateField(verbose_name='publication date')),
                ('format', models.CharField(max_length=254)),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('genre', models.ManyToManyField(blank=True, null=True, to='products.Genre')),
            ],
        ),
    ]
