# Generated by Django 3.2 on 2022-01-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
