# Generated by Django 3.2 on 2022-06-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220625_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn13',
            field=models.CharField(max_length=13),
        ),
    ]
