# Generated by Django 3.2 on 2022-06-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220625_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn13',
            field=models.CharField(error_messages={'min_length': 'Please enter 13 characters for ISBN13.'}, max_length=13),
        ),
    ]
